### ISSUE TITLE
login Google Account failed

### ISSUE THREAD

**Issue by pedia** [pgodschalk/swiperproxy#25]
Login with [Google Account](https://proxy.donttrustrobots.nl/accounts.google.com/ServiceLogin?hl=en&passive=true&continue=https://www.google.com/) failed.  

Hope resolve it. Thanks.

**Comment by Techwolf12** [comment]
After you go through the login process you will end up on the Google homepage not logged in. 
Not sure what it is yet however it is certainly a bug.
